### ISSUE TITLE
AttributeError: module 'geomstats.spd_matrices_space' has no attribute 'group_log'

### ISSUE THREAD

**Issue by petrapoklukar** [geomstats/examples#19]
Hi, 

I tried to run the brain_connectome example but I get the following error

```python
AttributeError: module 'geomstats.spd_matrices_space' has no attribute 'group_log'
```
that is raised when trying to compute the distances, e.g., 

```python
def frobenius(hat_l1, hat_l2):
    return np.linalg.norm(spd_space.group_log(hat_l1).squeeze(0)
                          - spd_space.group_log(hat_l2).squeeze(0),
                          'fro')
```

Any idea where to find group_log function?

Thanks, 
Petra

**Comment by ninamiolane** [comment]
This is probably due to the recent refactorization in geomstats library. Let me have a look at this and come back to you asap. Thanks for catching it!
