### ISSUE TITLE
Riemannian distance on SPDMatricesSpace is not symmetric in its arguments

### ISSUE THREAD

**Issue by petrapoklukar** [geomstats/examples#21]
Hi, 

I am trying to reuse your implementation of Riemannian distance on a manifold of SPD matrices as in the *brain_connectome* example but I noticed that the distance function is not symmetric in its arguments. For example, I have two SPD matrices *M_train* and *M_test* for which the code
```python
SPACE = spd_space.SPDMatricesSpace(n=8)
print(SPACE.belongs(M_test))
print(SPACE.belongs(M_train))
```
returns *True*. If I then compute the corresponding square root inverses as in your example
```python
lambda2_test, u_test = np.linalg.eigh(M_test)
inv_test = u_test.dot(np.diag(1.0/np.sqrt(lambda2_test)).dot(u_test.T))
    
lambda2_train, u_train = np.linalg.eigh(M_train)
inv_train = u_train.dot(np.diag(1./np.sqrt(lambda2_train)).dot(u_train.T))
```
I get the following result when computing the Riemannian distance
```python
riemannian(inv_test, M_train) = 4.67188330737327
riemannian(inv_train, M_test) = 2.223826153286933
```
which is clearly not symmetric as one would expect by the definition of a metric. Now I am starting to wonder if your implementation of the Riemannian distance 
```python
def riemannian(inv_l1, hat_l2):
    log_2 = SPACE.embedding_manifold.group_log(hat_l2).squeeze(0)
    return np.linalg.norm(inv_l1.dot(log_2.dot(inv_l1)), 'fro')
```
is specific to your example and is relying on some characteristics of regularized Laplacian SPD matrices that I am not aware of, or could it be used in a general case when dealing with SPD matrices? If not, what would be the correct way of computing it in my case?

Best, 
Petra

**Comment by ninamiolane** [comment]
Hello - thank you for your interest! We will look at this and come back to you asap.

**Comment by ninamiolane** [comment]
Thank you for catching this. A new PR has addressed it. In the brain_connectome folder:

```
import geomstats.backend as gs
import spd_fmri as spd

a = spd.SPACE.random_uniform()
b = spd.SPACE.random_uniform()

spd.riemannian(a, b)
spd.riemannian(b, a)

ainv = gs.linalg.inv(a)
binv = gs.linalg.inv(b)

spd.riemannian(ainv, b)
spd.riemannian(a, binv)
```

If you want to compute on the space of SPD matrices - independently of the brain connectome example - we recommend that you call the functions from /geomstats/spd_matrices_space.py which have been unit tested. For example:

```
import geomstats.spd_matrices_space as spd
space = space.SPDMatricesSpace(n=5)
metric = space.metric

a = space.random_uniform()
b = space.random_uniform()

dist = metric.dist(a, b)
```
and other functions.

**Comment by petrapoklukar** [comment]
Awesome, thanks for your answer!

Petra
